-- CrisisControl Supabase/Postgres schema foundation
-- Designed for scalable hotel operations, auth, alerts, SMS, AR model inputs, and audit trails.

create extension if not exists pgcrypto;

-- Profiles extend Supabase auth.users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text unique not null,
  role text not null check (role in ('admin', 'security', 'staff', 'maintenance', 'super_admin')),
  avatar_url text,
  phone text,
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_email on public.profiles(email);

-- Buildings and floor plans
create table if not exists public.buildings (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text unique not null,
  address text,
  timezone text not null default 'UTC',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.floors (
  id uuid primary key default gen_random_uuid(),
  building_id uuid not null references public.buildings(id) on delete cascade,
  name text not null,
  level integer not null,
  plan_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (building_id, level)
);

create table if not exists public.zones (
  id uuid primary key default gen_random_uuid(),
  building_id uuid not null references public.buildings(id) on delete cascade,
  floor_id uuid references public.floors(id) on delete set null,
  name text not null,
  zone_type text not null default 'general' check (zone_type in ('general', 'exit', 'staircase', 'lobby', 'corridor', 'room', 'service')),
  status text not null default 'safe' check (status in ('safe', 'risk', 'blocked')),
  geo jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_zones_building on public.zones(building_id);
create index if not exists idx_zones_floor on public.zones(floor_id);
create index if not exists idx_zones_status on public.zones(status);

-- Operational events generated by AI / sensors / decision engine
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  building_id uuid not null references public.buildings(id) on delete cascade,
  floor_id uuid references public.floors(id) on delete set null,
  zone_id uuid references public.zones(id) on delete set null,
  event_type text not null check (event_type in ('fire', 'smoke', 'fall', 'crowd', 'security', 'medical', 'system', 'alarm')),
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'active' check (status in ('active', 'acknowledged', 'resolved', 'suppressed')),
  title text not null,
  description text,
  source text not null default 'ai_model',
  metadata jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_events_building_status on public.events(building_id, status);
create index if not exists idx_events_detected_at on public.events(detected_at desc);
create index if not exists idx_events_severity on public.events(severity);

-- Event lifecycle log for auditability
create table if not exists public.event_actions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_event_actions_event on public.event_actions(event_id);
create index if not exists idx_event_actions_actor on public.event_actions(actor_id);

-- Broadcast messaging for floors / roles / individuals
create table if not exists public.broadcasts (
  id uuid primary key default gen_random_uuid(),
  building_id uuid not null references public.buildings(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  audience_type text not null check (audience_type in ('all', 'floor', 'individual', 'role', 'custom')),
  audience_value text,
  message text not null,
  delivery_mode text not null default 'sms' check (delivery_mode in ('sms', 'push', 'email', 'all')),
  priority text not null default 'normal' check (priority in ('normal', 'urgent', 'critical')),
  status text not null default 'queued' check (status in ('queued', 'sending', 'sent', 'partial', 'failed')),
  recipient_count integer not null default 0,
  success_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.broadcast_recipients (
  id uuid primary key default gen_random_uuid(),
  broadcast_id uuid not null references public.broadcasts(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete set null,
  phone text,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_broadcasts_building_created on public.broadcasts(building_id, created_at desc);
create index if not exists idx_broadcasts_status on public.broadcasts(status);
create index if not exists idx_broadcast_recipients_broadcast on public.broadcast_recipients(broadcast_id);

-- Audit trail for everything important
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  building_id uuid references public.buildings(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_building_created on public.audit_logs(building_id, created_at desc);
create index if not exists idx_audit_logs_actor on public.audit_logs(actor_id);

-- AI / computer vision model outputs, including spread prediction and crowd status
create table if not exists public.model_events (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references public.events(id) on delete set null,
  model_type text not null check (model_type in ('fire_smoke', 'fall', 'crowd', 'route', 'system')),
  prediction text not null,
  confidence numeric(5,4) not null check (confidence >= 0 and confidence <= 1),
  frame_uri text,
  frame_index integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_model_events_created on public.model_events(created_at desc);
create index if not exists idx_model_events_model_type on public.model_events(model_type);

-- Route planning and evacuation guidance
create table if not exists public.routes (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references public.events(id) on delete cascade,
  building_id uuid not null references public.buildings(id) on delete cascade,
  from_zone_id uuid references public.zones(id) on delete set null,
  to_zone_id uuid references public.zones(id) on delete set null,
  route_type text not null default 'evacuation' check (route_type in ('evacuation', 'staff', 'service')),
  path jsonb not null,
  safety_score numeric(5,4) not null default 0,
  distance_meters numeric(10,2),
  eta_seconds integer,
  status text not null default 'active' check (status in ('active', 'superseded', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_routes_event on public.routes(event_id);
create index if not exists idx_routes_building_status on public.routes(building_id, status);

-- Timestamps helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Apply updated_at trigger across mutable tables
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger trg_buildings_updated_at before update on public.buildings for each row execute function public.set_updated_at();
create trigger trg_floors_updated_at before update on public.floors for each row execute function public.set_updated_at();
create trigger trg_zones_updated_at before update on public.zones for each row execute function public.set_updated_at();
create trigger trg_events_updated_at before update on public.events for each row execute function public.set_updated_at();
create trigger trg_broadcasts_updated_at before update on public.broadcasts for each row execute function public.set_updated_at();
create trigger trg_broadcast_recipients_updated_at before update on public.broadcast_recipients for each row execute function public.set_updated_at();
create trigger trg_routes_updated_at before update on public.routes for each row execute function public.set_updated_at();

-- Row-level security can be enabled once auth is wired.
-- alter table public.profiles enable row level security;
-- alter table public.events enable row level security;
-- alter table public.broadcasts enable row level security;
-- alter table public.audit_logs enable row level security;
